public class apifeatures {
    // I got this form DR-Droid
// #the complete API's lists
// #this is the Api list from karim's tool using for identify the senstive apis 
// # not onlty include the apis from android os but also includes from java standard library
    public String[] androidAPIs = {
        "Landroid/telephony/gsm/SmsManager", 
        "Landroid/telephony/gsm/SmsManager",
        "Landroid/telephony/SmsManager",
        "Landroid/telephony/SmsManager",  
        "Landroid/telephony/SmsManager", 
        "Landroid/telephony/SmsManager",
        "Landroid/telephony/TelephonyManager",      
        "Landroid/telephony/TelephonyManager",
        "Landroid/telephony/TelephonyManager",
     	"Lorg/apache/http/impl/client/DefaultHttpClient",
        "Lorg/apache/http/client/HttpClient",
        "Landroid/net/http/AndroidHttpClient",
        "Landroid/location/Location",
        "Landroid/location/Location",
        "Landroid/location/Location",
        "Landroid/location/Location",         
        "Landroid/telephony/TelephonyManager",       
        "Landroid/telephony/TelephonyManager",
        "Landroid/telephony/TelephonyManagerr",      
        "Landroid/telephony/TelephonyManager",       
        "Landroid/telephony/TelephonyManager",     
        "Landroid/telephony/TelephonyManager",              
        "Landroid/telephony/TelephonyManager",    
        "Landroid/content/ContentResolver",
        "Landroid/content/ContentResolver",
        "Landroid/content/ContentResolver",
        "Landroid/database/sqlite/SQLiteDatabase",
        "Landroid/database/sqlite/SQLiteDatabase",       
        "Landroid/database/sqlite/SQLiteDatabase",      
        "Landroid/database/sqlite/SQLiteDatabase", 
	    "Landroid/net/wifi/WifiInfo",
 	    "Landroid/net/wifi/WifiInfo",
        "Landroid/net/wifi/WifiInfo",
        "Landroid/net/wifi/WifiInfo",
        "Landroid/net/wifi/WifiInfo",
        "Landroid/net/wifi/WifiInfo",
	    "Landroid/accounts/AccountManager",
	    "Landroid/accounts/AccountManager",
        "Landroid/app/ActivityManager", 
        "Landroid/app/ActivityManager",
    };
public String[] javaAPIs = {
    "Ljava/lang/Runtime",
    "Ljava/io/FileOutputStream",
    "Ljava/io/OutputStream",
    "Ljava/io/BufferedWriter",
    "Ljava/io/FileInputStream",
    "Ljava/io/InputStream",
    "Ljava/io/BufferedReader",
    "Ljava/io/BufferedReader",
    "Ljava/io/FileInputStream",
    "Ljava/io/FileOutputStream",    
    "Ljava/io/File",    
    "Ljava/io/File",
    "Ljava/io/File",  
    "Ljava/io/File",
    "Ljava/net/Socket",
    "Ljava/net/DatagramSocket",
    "Ljava/net/DatagramSocket"
};

// #// access of phone identifier APIs
// #sinkNames.add("getCellLocation");   
// TODo can exterend the list for more ... 
// """
//         "Ljava/lang/Runtime; exec",
//         "Ljava/io/FileOutputStream; write",
//         "Ljava/io/OutputStream; write",
//         "Ljava/io/BufferedWriter; write",
//         "Ljava/io/FileInputStream; read",
//         "Ljava/io/InputStream; read",
//         "Ljava/io/BufferedReader; readLine",
//         "Ljava/io/BufferedReader; read",
//         "Ljava/io/FileInputStream; openFileInput",
//         "Ljava/io/FileOutputStream; openFileOutput",    
//         "Ljava/io/File; createNewFile",    
//         "Ljava/io/File; createTempFile",
//         "Ljava/io/File; delete",  
//         "Ljava/io/File; deleteOnExit",
//         "Ljava/net/Socket; sendUrgentData",
//         "Ljava/net/DatagramSocket; receive",
//         "Ljava/net/DatagramSocket; send",
// """

// #this part is for user triggering interactions
    public String[] userActionList = {
        "onClick",
        "onListItemClick", 
        "onOptionsItemSelected",
        "onMenuItemClick",
        "onContextItemSelected", 
        "onKey",
        "onKeyDown",
        "onKeyLongPress",
        "onTouch",
        "onItemSelected", 
        "onRadioButtonClicked",
        "onToggleClicked", 
        "onCheckboxClicked", 
        "onPictureTaken",
        "onLongClick",       
        "onItemLongClick",
        "boolean performClick",
        "performLongClick",
        "performItemClick",
        "onTabChanged",
        "onEditorAction", 
        "onTabSelected",
        "onTabReselected",
        "onCheckedChanged",
        "onDrag",
        "onRatingChanged", 
        "onClose",
        "onLocationChanged",         
        "onProgressChanged",
        "onPreferenceClick", 
        "onItemClick", 
        "onQueryTextChange", 
        "onQueryTextSubmit",  
        "onTextChanged",
        "afterTextChanged"
    };
};


// public String[] DVM_PERMISSIONS_BY_ELEMENT = { 
// 	"Landroid/net/sip/SipAudioCall; startAudio" : "RECORD_AUDIO",
// 	"Landroid/os/Debug; dumpService" : "DUMP",
// 	"Landroid/os/IBinder; DUMP_TRANSACTION-I" : "DUMP",
// 	"Landroid/location/LocationManager; addTestProvider" : "ACCESS_MOCK_LOCATION",
// 	"Landroid/location/LocationManager;-clearTestProviderEnabled-(Ljava/lang/String;)V" : "ACCESS_MOCK_LOCATION",
// 	"Landroid/location/LocationManager;-clearTestProviderLocation-(Ljava/lang/String;)V" : "ACCESS_MOCK_LOCATION",
// 	"Landroid/location/LocationManager;-clearTestProviderStatus-(Ljava/lang/String;)V" : "ACCESS_MOCK_LOCATION",
// 	"Landroid/location/LocationManager;-removeTestProvider-(Ljava/lang/String;)V" : "ACCESS_MOCK_LOCATION",
// 	"Landroid/location/LocationManager;-setTestProviderEnabled-(Ljava/lang/String; B)V" : "ACCESS_MOCK_LOCATION",
// 	"Landroid/location/LocationManager;-setTestProviderLocation-(Ljava/lang/String; Landroid/location/Location;)V" : "ACCESS_MOCK_LOCATION",
// 	"Landroid/location/LocationManager;-setTestProviderStatus-(Ljava/lang/String; I Landroid/os/Bundle; J)V" : "ACCESS_MOCK_LOCATION",
// 	"Landroid/accounts/AccountManager;-blockingGetAuthToken-(Landroid/accounts/Account; Ljava/lang/String; B)Ljava/lang/String;" : "USE_CREDENTIALS",
// 	"Landroid/accounts/AccountManager;-getAuthToken-(Landroid/accounts/Account; Ljava/lang/String; Landroid/os/Bundle; Landroid/app/Activity; Landroid/accounts/AccountManagerCallback<android/os/Bundle>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "USE_CREDENTIALS",
// 	"Landroid/accounts/AccountManager;-getAuthToken-(Landroid/accounts/Account; Ljava/lang/String; B Landroid/accounts/AccountManagerCallback<android/os/Bundle>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "USE_CREDENTIALS",
// 	"Landroid/accounts/AccountManager;-invalidateAuthToken-(Ljava/lang/String; Ljava/lang/String;)V" : "USE_CREDENTIALS",
// 	"Landroid/telephony/gsm/SmsManager;-getDefault-()Landroid/telephony/gsm/SmsManager;" : "SEND_SMS",
// 	"Landroid/telephony/gsm/SmsManager;-sendDataMessage-(Ljava/lang/String; Ljava/lang/String; S [B Landroid/app/PendingIntent; Landroid/app/PendingIntent;)V" : "SEND_SMS",
// 	"Landroid/telephony/gsm/SmsManager;-sendTextMessage-(Ljava/lang/String; Ljava/lang/String; Ljava/lang/String; Landroid/app/PendingIntent; Landroid/app/PendingIntent;)V" : "SEND_SMS",
// 	"Landroid/telephony/SmsManager;-getDefault-()Landroid/telephony/SmsManager;" : "SEND_SMS",
// 	"Landroid/telephony/SmsManager;-sendDataMessage-(Ljava/lang/String; Ljava/lang/String; S [B Landroid/app/PendingIntent; Landroid/app/PendingIntent;)V" : "SEND_SMS",
// 	"Landroid/telephony/SmsManager;-sendTextMessage-(Ljava/lang/String; Ljava/lang/String; Ljava/lang/String; Landroid/app/PendingIntent; Landroid/app/PendingIntent;)V" : "SEND_SMS",
// 	"Landroid/provider/Settings/System;-VIBRATE_ON-Ljava/lang/String;" : "VIBRATE",
// 	"Landroid/app/Notification;-DEFAULT_VIBRATE-I" : "VIBRATE",
// 	"Landroid/app/Notification;-defaults-I" : "VIBRATE",
// 	"Landroid/app/Notification/Builder;-setDefaults-(I)LNotification/Builder;" : "VIBRATE",
// 	"Landroid/media/AudioManager;-EXTRA_RINGER_MODE-Ljava/lang/String;" : "VIBRATE",
// 	"Landroid/media/AudioManager;-EXTRA_VIBRATE_SETTING-Ljava/lang/String;" : "VIBRATE",
// 	"Landroid/media/AudioManager;-EXTRA_VIBRATE_TYPE-Ljava/lang/String;" : "VIBRATE",
// 	"Landroid/media/AudioManager;-FLAG_REMOVE_SOUND_AND_VIBRATE-I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-FLAG_VIBRATE-I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-RINGER_MODE_VIBRATE-I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-VIBRATE_SETTING_CHANGED_ACTION-Ljava/lang/String;" : "VIBRATE",
// 	"Landroid/media/AudioManager;-VIBRATE_SETTING_OFF-I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-VIBRATE_SETTING_ON-I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-VIBRATE_SETTING_ONLY_SILENT-I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-VIBRATE_TYPE_NOTIFICATION-I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-VIBRATE_TYPE_RINGER-I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-getRingerMode-()I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-getVibrateSetting-(I)I" : "VIBRATE",
// 	"Landroid/media/AudioManager;-setRingerMode-(I)V" : "VIBRATE",
// 	"Landroid/media/AudioManager;-setVibrateSetting-(I I)V" : "VIBRATE",
// 	"Landroid/media/AudioManager;-shouldVibrate-(I)B" : "VIBRATE",
// 	"Landroid/telephony/TelephonyManager;-getCellLocation-()Landroid/telephony/CellLocation;" : "ACCESS_COARSE_LOCATION",
// 	"Landroid/telephony/PhoneStateListener;-LISTEN_CELL_LOCATION-I" : "ACCESS_COARSE_LOCATION",
// 	"Landroid/location/LocationManager;-NETWORK_PROVIDER-Ljava/lang/String;" : "ACCESS_COARSE_LOCATION",
// 	"Landroid/app/admin/DeviceAdminReceiver;-ACTION_DEVICE_ADMIN_ENABLED-Ljava/lang/String;" : "BIND_DEVICE_ADMIN",
// 	"Landroid/os/DropBoxManager;-ACTION_DROPBOX_ENTRY_ADDED-Ljava/lang/String;" : "READ_LOGS",
// 	"Landroid/os/DropBoxManager;-getNextEntry-(Ljava/lang/String; J)LDropBoxManager/Entry;" : "READ_LOGS",
// 	"Landroid/content/Intent;-ACTION_NEW_OUTGOING_CALL-Ljava/lang/String;" : "PROCESS_OUTGOING_CALLS",
// 	"Landroid/telephony/TelephonyManager;-getCellLocation-()Landroid/telephony/CellLocation;" : "ACCESS_FINE_LOCATION",
// 	"Landroid/location/LocationManager;-GPS_PROVIDER-Ljava/lang/String;" : "ACCESS_FINE_LOCATION",
// 	"Landroid/location/LocationManager;-NETWORK_PROVIDER-Ljava/lang/String;" : "ACCESS_FINE_LOCATION",
// 	"Landroid/location/LocationManager;-PASSIVE_PROVIDER-Ljava/lang/String;" : "ACCESS_FINE_LOCATION",
// 	"Landroid/location/LocationManager;-addGpsStatusListener-(Landroid/location/GpsStatus/Listener;)B" : "ACCESS_FINE_LOCATION",
// 	"Landroid/location/LocationManager;-addNmeaListener-(Landroid/location/GpsStatus/NmeaListener;)B" : "ACCESS_FINE_LOCATION",
// 	"Landroid/app/SearchManager;-EXTRA_SELECT_QUERY-Ljava/lang/String;" : "GLOBAL_SEARCH",
// 	"Landroid/app/SearchManager;-INTENT_ACTION_GLOBAL_SEARCH-Ljava/lang/String;" : "GLOBAL_SEARCH",
// 	"Landroid/content/Context;-removeStickyBroadcast-(Landroid/content/Intent;)V" : "BROADCAST_STICKY",
// 	"Landroid/content/Context;-sendStickyBroadcast-(Landroid/content/Intent;)V" : "BROADCAST_STICKY",
// 	"Landroid/content/ContextWrapper;-removeStickyBroadcast-(Landroid/content/Intent;)V" : "BROADCAST_STICKY",
// 	"Landroid/content/ContextWrapper;-sendStickyBroadcast-(Landroid/content/Intent;)V" : "BROADCAST_STICKY",
// 	"Landroid/service/wallpaper/WallpaperService;-SERVICE_INTERFACE-Ljava/lang/String;" : "BIND_WALLPAPER",
// 	"Landroid/app/ActivityManager;-killBackgroundProcesses-(Ljava/lang/String;)V" : "KILL_BACKGROUND_PROCESSES",
// 	"Landroid/app/AlarmManager;-setTimeZone-(Ljava/lang/String;)V" : "SET_TIME_ZONE",
// 	"Landroid/bluetooth/BluetoothAdapter;-cancelDiscovery-()B" : "BLUETOOTH_ADMIN",
// 	"Landroid/bluetooth/BluetoothAdapter;-disable-()B" : "BLUETOOTH_ADMIN",
// 	"Landroid/bluetooth/BluetoothAdapter;-enable-()B" : "BLUETOOTH_ADMIN",
// 	"Landroid/bluetooth/BluetoothAdapter;-setName-(Ljava/lang/String;)B" : "BLUETOOTH_ADMIN",
// 	"Landroid/bluetooth/BluetoothAdapter;-startDiscovery-()B" : "BLUETOOTH_ADMIN",
// 	"Landroid/view/View/OnSystemUiVisibilityChangeListener;-onSystemUiVisibilityChange-(I)V" : "STATUS_BAR",
// 	"Landroid/view/View;-STATUS_BAR_HIDDEN-I" : "STATUS_BAR",
// 	"Landroid/view/View;-STATUS_BAR_VISIBLE-I" : "STATUS_BAR",
// 	"Landroid/view/WindowManager/LayoutParams;-TYPE_STATUS_BAR-I" : "STATUS_BAR",
// 	"Landroid/view/WindowManager/LayoutParams;-TYPE_STATUS_BAR_PANEL-I" : "STATUS_BAR",
// 	"Landroid/view/WindowManager/LayoutParams;-systemUiVisibility-I" : "STATUS_BAR",
// 	"Landroid/view/WindowManager/LayoutParams;-type-I" : "STATUS_BAR",
// 	"Landroid/hardware/Camera/ErrorCallback;-onError-(I Landroid/hardware/Camera;)V" : "CAMERA",
// 	"Landroid/bluetooth/BluetoothClass/Device;-AUDIO_VIDEO_VIDEO_CAMERA-I" : "CAMERA",
// 	"Landroid/content/pm/PackageManager;-FEATURE_CAMERA-Ljava/lang/String;" : "CAMERA",
// 	"Landroid/content/pm/PackageManager;-FEATURE_CAMERA_AUTOFOCUS-Ljava/lang/String;" : "CAMERA",
// 	"Landroid/content/pm/PackageManager;-FEATURE_CAMERA_FLASH-Ljava/lang/String;" : "CAMERA",
// 	"Landroid/content/pm/PackageManager;-FEATURE_CAMERA_FRONT-Ljava/lang/String;" : "CAMERA",
// 	"Landroid/view/KeyEvent;-KEYCODE_CAMERA-I" : "CAMERA",
// 	"Landroid/provider/MediaStore;-INTENT_ACTION_STILL_IMAGE_CAMERA-Ljava/lang/String;" : "CAMERA",
// 	"Landroid/provider/MediaStore;-INTENT_ACTION_VIDEO_CAMERA-Ljava/lang/String;" : "CAMERA",
// 	"Landroid/hardware/Camera/CameraInfo;-CAMERA_FACING_BACK-I" : "CAMERA",
// 	"Landroid/hardware/Camera/CameraInfo;-CAMERA_FACING_FRONT-I" : "CAMERA",
// 	"Landroid/hardware/Camera/CameraInfo;-facing-I" : "CAMERA",
// 	"Landroid/provider/ContactsContract/StatusColumns;-CAPABILITY_HAS_CAMERA-I" : "CAMERA",
// 	"Landroid/hardware/Camera/Parameters;-setRotation-(I)V" : "CAMERA",
// 	"Landroid/media/MediaRecorder/VideoSource;-CAMERA-I" : "CAMERA",
// 	"Landroid/content/Intent;-IntentResolution-Ljava/lang/String;" : "CAMERA",
// 	"Landroid/content/Intent;-ACTION_CAMERA_BUTTON-Ljava/lang/String;" : "CAMERA",
// 	"Landroid/hardware/Camera;-CAMERA_ERROR_SERVER_DIED-I" : "CAMERA",
// 	"Landroid/hardware/Camera;-CAMERA_ERROR_UNKNOWN-I" : "CAMERA",
// 	"Landroid/hardware/Camera;-setDisplayOrientation-(I)V" : "CAMERA",
// 	"Landroid/app/WallpaperManager;-setBitmap-(Landroid/graphics/Bitmap;)V" : "SET_WALLPAPER",
// 	"Landroid/net/sip/SipAudioCall;-startAudio-()V" : "WAKE_LOCK",
// 	"Landroid/media/MediaPlayer;-setWakeMode-(Landroid/content/Context; I)V" : "WAKE_LOCK",
// 	"Landroid/os/PowerManager;-ACQUIRE_CAUSES_WAKEUP-I" : "WAKE_LOCK",
// 	"Landroid/os/PowerManager;-FULL_WAKE_LOCK-I" : "WAKE_LOCK",
// 	"Landroid/os/PowerManager;-ON_AFTER_RELEASE-I" : "WAKE_LOCK",
// 	"Landroid/os/PowerManager;-PARTIAL_WAKE_LOCK-I" : "WAKE_LOCK",
// 	"Landroid/os/PowerManager;-SCREEN_BRIGHT_WAKE_LOCK-I" : "WAKE_LOCK",
// 	"Landroid/os/PowerManager;-SCREEN_DIM_WAKE_LOCK-I" : "WAKE_LOCK",
// 	"Landroid/os/PowerManager;-newWakeLock-(I Ljava/lang/String;)LPowerManager/WakeLock;" : "WAKE_LOCK",
// 	"Landroid/accounts/AccountManager;-addAccount-(Ljava/lang/String; Ljava/lang/String; [Ljava/lang/String; Landroid/os/Bundle; Landroid/app/Activity; Landroid/accounts/AccountManagerCallback<android/os/Bundle>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "MANAGE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-clearPassword-(Landroid/accounts/Account;)V" : "MANAGE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-confirmCredentials-(Landroid/accounts/Account; Landroid/os/Bundle; Landroid/app/Activity; Landroid/accounts/AccountManagerCallback<android/os/Bundle>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "MANAGE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-editProperties-(Ljava/lang/String; Landroid/app/Activity; Landroid/accounts/AccountManagerCallback<android/os/Bundle>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "MANAGE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-getAuthTokenByFeatures-(Ljava/lang/String; Ljava/lang/String; [Ljava/lang/String; Landroid/app/Activity; Landroid/os/Bundle; Landroid/os/Bundle; Landroid/accounts/AccountManagerCallback<android/os/Bundle>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "MANAGE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-invalidateAuthToken-(Ljava/lang/String; Ljava/lang/String;)V" : "MANAGE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-removeAccount-(Landroid/accounts/Account; Landroid/accounts/AccountManagerCallback<java/lang/Boolean>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "MANAGE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-updateCredentials-(Landroid/accounts/Account; Ljava/lang/String; Landroid/os/Bundle; Landroid/app/Activity; Landroid/accounts/AccountManagerCallback<android/os/Bundle>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "MANAGE_ACCOUNTS",
// 	"Landroid/provider/Browser;-BOOKMARKS_URI-Landroid/net/Uri;" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-SEARCHES_URI-Landroid/net/Uri;" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-addSearchUrl-(Landroid/content/ContentResolver; Ljava/lang/String;)V" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-clearHistory-(Landroid/content/ContentResolver;)V" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-clearSearches-(Landroid/content/ContentResolver;)V" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-deleteFromHistory-(Landroid/content/ContentResolver; Ljava/lang/String;)V" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-deleteHistoryTimeFrame-(Landroid/content/ContentResolver; J J)V" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-truncateHistory-(Landroid/content/ContentResolver;)V" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-updateVisitedHistory-(Landroid/content/ContentResolver; Ljava/lang/String; B)V" : "WRITE_HISTORY_BOOKMARKS",
// 	"Landroid/content/Intent;-ACTION_BOOT_COMPLETED-Ljava/lang/String;" : "RECEIVE_BOOT_COMPLETED",
// 	"Landroid/provider/AlarmClock;-ACTION_SET_ALARM-Ljava/lang/String;" : "SET_ALARM",
// 	"Landroid/provider/AlarmClock;-EXTRA_HOUR-Ljava/lang/String;" : "SET_ALARM",
// 	"Landroid/provider/AlarmClock;-EXTRA_MESSAGE-Ljava/lang/String;" : "SET_ALARM",
// 	"Landroid/provider/AlarmClock;-EXTRA_MINUTES-Ljava/lang/String;" : "SET_ALARM",
// 	"Landroid/provider/AlarmClock;-EXTRA_SKIP_UI-Ljava/lang/String;" : "SET_ALARM",
// 	"Landroid/inputmethodservice/InputMethodService;-SoftInputView-I" : "NFC",
// 	"Landroid/inputmethodservice/InputMethodService;-CandidatesView-I" : "NFC",
// 	"Landroid/inputmethodservice/InputMethodService;-FullscreenMode-I" : "NFC",
// 	"Landroid/inputmethodservice/InputMethodService;-GeneratingText-I" : "NFC",
// 	"Landroid/nfc/tech/NfcA;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/NfcA;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/NfcA;-get-(Landroid/nfc/Tag;)" : "NFC",
// 	"Landroid/nfc/tech/NfcA;-transceive-([B)[B" : "NFC",
// 	"Landroid/nfc/tech/NfcB;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/NfcB;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/NfcB;-get-(Landroid/nfc/Tag;)" : "NFC",
// 	"Landroid/nfc/tech/NfcB;-transceive-([B)[B" : "NFC",
// 	"Landroid/nfc/NfcAdapter;-ACTION_TECH_DISCOVERED-Ljava/lang/String;" : "NFC",
// 	"Landroid/nfc/NfcAdapter;-disableForegroundDispatch-(Landroid/app/Activity;)V" : "NFC",
// 	"Landroid/nfc/NfcAdapter;-disableForegroundNdefPush-(Landroid/app/Activity;)V" : "NFC",
// 	"Landroid/nfc/NfcAdapter;-enableForegroundDispatch-(Landroid/app/Activity; Landroid/app/PendingIntent; [Landroid/content/IntentFilter; [[Ljava/lang/String[];)V" : "NFC",
// 	"Landroid/nfc/NfcAdapter;-enableForegroundNdefPush-(Landroid/app/Activity; Landroid/nfc/NdefMessage;)V" : "NFC",
// 	"Landroid/nfc/NfcAdapter;-getDefaultAdapter-()" : "NFC",
// 	"Landroid/nfc/NfcAdapter;-getDefaultAdapter-(Landroid/content/Context;)" : "NFC",
// 	"Landroid/nfc/NfcAdapter;-isEnabled-()B" : "NFC",
// 	"Landroid/nfc/tech/NfcF;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/NfcF;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/NfcF;-get-(Landroid/nfc/Tag;)" : "NFC",
// 	"Landroid/nfc/tech/NfcF;-transceive-([B)[B" : "NFC",
// 	"Landroid/nfc/tech/NdefFormatable;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/NdefFormatable;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/NdefFormatable;-format-(Landroid/nfc/NdefMessage;)V" : "NFC",
// 	"Landroid/nfc/tech/NdefFormatable;-formatReadOnly-(Landroid/nfc/NdefMessage;)V" : "NFC",
// 	"Landroid/app/Activity;-Fragments-I" : "NFC",
// 	"Landroid/app/Activity;-ActivityLifecycle-I" : "NFC",
// 	"Landroid/app/Activity;-ConfigurationChanges-I" : "NFC",
// 	"Landroid/app/Activity;-StartingActivities-I" : "NFC",
// 	"Landroid/app/Activity;-SavingPersistentState-I" : "NFC",
// 	"Landroid/app/Activity;-Permissions-I" : "NFC",
// 	"Landroid/app/Activity;-ProcessLifecycle-I" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-KEY_NFC_FORUM-[B" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-authenticateSectorWithKeyA-(I [B)B" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-authenticateSectorWithKeyB-(I [B)B" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-decrement-(I I)V" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-increment-(I I)V" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-readBlock-(I)[B" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-restore-(I)V" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-transceive-([B)[B" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-transfer-(I)V" : "NFC",
// 	"Landroid/nfc/tech/MifareClassic;-writeBlock-(I [B)V" : "NFC",
// 	"Landroid/nfc/Tag;-getTechList-()[Ljava/lang/String;" : "NFC",
// 	"Landroid/app/Service;-WhatIsAService-I" : "NFC",
// 	"Landroid/app/Service;-ServiceLifecycle-I" : "NFC",
// 	"Landroid/app/Service;-Permissions-I" : "NFC",
// 	"Landroid/app/Service;-ProcessLifecycle-I" : "NFC",
// 	"Landroid/app/Service;-LocalServiceSample-I" : "NFC",
// 	"Landroid/app/Service;-RemoteMessengerServiceSample-I" : "NFC",
// 	"Landroid/nfc/NfcManager;-getDefaultAdapter-()" : "NFC",
// 	"Landroid/nfc/tech/MifareUltralight;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/MifareUltralight;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/MifareUltralight;-readPages-(I)[B" : "NFC",
// 	"Landroid/nfc/tech/MifareUltralight;-transceive-([B)[B" : "NFC",
// 	"Landroid/nfc/tech/MifareUltralight;-writePage-(I [B)V" : "NFC",
// 	"Landroid/nfc/tech/NfcV;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/NfcV;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/NfcV;-get-(Landroid/nfc/Tag;)" : "NFC",
// 	"Landroid/nfc/tech/NfcV;-transceive-([B)[B" : "NFC",
// 	"Landroid/nfc/tech/TagTechnology;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/TagTechnology;-connect-()V" : "NFC",
// 	"Landroid/preference/PreferenceActivity;-SampleCode-Ljava/lang/String;" : "NFC",
// 	"Landroid/content/pm/PackageManager;-FEATURE_NFC-Ljava/lang/String;" : "NFC",
// 	"Landroid/content/Context;-NFC_SERVICE-Ljava/lang/String;" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-NFC_FORUM_TYPE_1-Ljava/lang/String;" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-NFC_FORUM_TYPE_2-Ljava/lang/String;" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-NFC_FORUM_TYPE_3-Ljava/lang/String;" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-NFC_FORUM_TYPE_4-Ljava/lang/String;" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-getType-()Ljava/lang/String;" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-isWritable-()B" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-makeReadOnly-()B" : "NFC",
// 	"Landroid/nfc/tech/Ndef;-writeNdefMessage-(Landroid/nfc/NdefMessage;)V" : "NFC",
// 	"Landroid/nfc/tech/IsoDep;-close-()V" : "NFC",
// 	"Landroid/nfc/tech/IsoDep;-connect-()V" : "NFC",
// 	"Landroid/nfc/tech/IsoDep;-setTimeout-(I)V" : "NFC",
// 	"Landroid/nfc/tech/IsoDep;-transceive-([B)[B" : "NFC",
// 	"Landroid/view/inputmethod/InputMethod;-SERVICE_INTERFACE-Ljava/lang/String;" : "BIND_INPUT_METHOD",
// 	"Landroid/content/pm/ApplicationInfo;-FLAG_FACTORY_TEST-I" : "FACTORY_TEST",
// 	"Landroid/content/pm/ApplicationInfo;-flags-I" : "FACTORY_TEST",
// 	"Landroid/content/Intent;-IntentResolution-Ljava/lang/String;" : "FACTORY_TEST",
// 	"Landroid/content/Intent;-ACTION_FACTORY_TEST-Ljava/lang/String;" : "FACTORY_TEST",
// 	"Landroid/accounts/AccountManager;-KEY_ACCOUNT_MANAGER_RESPONSE-Ljava/lang/String;" : "ACCOUNT_MANAGER",
// 	"Landroid/drm/DrmErrorEvent;-TYPE_NO_INTERNET_CONNECTION-I" : "INTERNET",
// 	"Landroid/accounts/AccountManager;-getAccounts-()" : "GET_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-getAccountsByType-(Ljava/lang/String;)" : "GET_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-getAccountsByTypeAndFeatures-(Ljava/lang/String; [Ljava/lang/String; [Landroid/accounts/AccountManagerCallback<android/accounts/Account[; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "GET_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-hasFeatures-(Landroid/accounts/Account; [Ljava/lang/String; Landroid/accounts/AccountManagerCallback<java/lang/Boolean>; Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;" : "GET_ACCOUNTS",
// 	"Landroid/app/AlarmManager;-setTime-(J)V" : "SET_TIME",
// 	"Landroid/app/AlarmManager;-setTimeZone-(Ljava/lang/String;)V" : "SET_TIME",
// 	"Landroid/accounts/AccountManager;-addAccountExplicitly-(Landroid/accounts/Account; Ljava/lang/String; Landroid/os/Bundle;)B" : "AUTHENTICATE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-getPassword-(Landroid/accounts/Account;)Ljava/lang/String;" : "AUTHENTICATE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-getUserData-(Landroid/accounts/Account; Ljava/lang/String;)Ljava/lang/String;" : "AUTHENTICATE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-peekAuthToken-(Landroid/accounts/Account; Ljava/lang/String;)Ljava/lang/String;" : "AUTHENTICATE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-setAuthToken-(Landroid/accounts/Account; Ljava/lang/String; Ljava/lang/String;)V" : "AUTHENTICATE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-setPassword-(Landroid/accounts/Account; Ljava/lang/String;)V" : "AUTHENTICATE_ACCOUNTS",
// 	"Landroid/accounts/AccountManager;-setUserData-(Landroid/accounts/Account; Ljava/lang/String; Ljava/lang/String;)V" : "AUTHENTICATE_ACCOUNTS",
// 	"Landroid/app/ActivityManager;-getRecentTasks-(I I)Ljava/util/List;" : "GET_TASKS",
// 	"Landroid/app/ActivityManager;-getRunningTasks-(I)Ljava/util/List;" : "GET_TASKS",
// 	"Landroid/provider/ContactsContract$CommonDataKinds$Phone;-CONTENT_URI-Landroid/net/Uri;" : "READ_CONTACTS",
// 	"Landroid/os/Build/VERSION_CODES;-DONUT-I" : "WRITE_EXTERNAL_STORAGE",
// 	"Landroid/app/DownloadManager/Request;-setDestinationUri-(Landroid/net/Uri;)Landroid/app/DownloadManager/Request;" : "WRITE_EXTERNAL_STORAGE",
// 	"Landroid/os/RecoverySystem;-installPackage-(Landroid/content/Context; Ljava/io/File;)V" : "REBOOT",
// 	"Landroid/os/RecoverySystem;-rebootWipeUserData-(Landroid/content/Context;)V" : "REBOOT",
// 	"Landroid/content/Intent;-IntentResolution-Ljava/lang/String;" : "REBOOT",
// 	"Landroid/content/Intent;-ACTION_REBOOT-Ljava/lang/String;" : "REBOOT",
// 	"Landroid/os/PowerManager;-reboot-(Ljava/lang/String;)V" : "REBOOT",
// 	"Landroid/bluetooth/BluetoothAdapter;-ACTION_CONNECTION_STATE_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-ACTION_DISCOVERY_FINISHED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-ACTION_DISCOVERY_STARTED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-ACTION_LOCAL_NAME_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-ACTION_REQUEST_DISCOVERABLE-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-ACTION_REQUEST_ENABLE-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-ACTION_SCAN_MODE_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-ACTION_STATE_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-cancelDiscovery-()B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-disable-()B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-enable-()B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-getAddress-()Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-getBondedDevices-()Ljava/util/Set;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-getName-()Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-getScanMode-()I" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-getState-()I" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-isDiscovering-()B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-isEnabled-()B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-listenUsingInsecureRfcommWithServiceRecord-(Ljava/lang/String; Ljava/util/UUID;)Landroid/bluetooth/BluetoothServerSocket;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-listenUsingRfcommWithServiceRecord-(Ljava/lang/String; Ljava/util/UUID;)Landroid/bluetooth/BluetoothServerSocket;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-setName-(Ljava/lang/String;)B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAdapter;-startDiscovery-()B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-ACTION_AUDIO_STATE_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-ACTION_CONNECTION_STATE_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-ACTION_VENDOR_SPECIFIC_HEADSET_EVENT-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-getConnectedDevices-()Ljava/util/List;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-getConnectionState-(Landroid/bluetooth/BluetoothDevice;)I" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-getDevicesMatchingConnectionStates-([I)Ljava/util/List;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-isAudioConnected-(Landroid/bluetooth/BluetoothDevice;)B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-startVoiceRecognition-(Landroid/bluetooth/BluetoothDevice;)B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothHeadset;-stopVoiceRecognition-(Landroid/bluetooth/BluetoothDevice;)B" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-ACTION_ACL_CONNECTED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-ACTION_ACL_DISCONNECTED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-ACTION_ACL_DISCONNECT_REQUESTED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-ACTION_BOND_STATE_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-ACTION_CLASS_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-ACTION_FOUND-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-ACTION_NAME_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-createInsecureRfcommSocketToServiceRecord-(Ljava/util/UUID;)Landroid/bluetooth/BluetoothSocket;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-createRfcommSocketToServiceRecord-(Ljava/util/UUID;)Landroid/bluetooth/BluetoothSocket;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-getBluetoothClass-()" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-getBondState-()I" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothDevice;-getName-()Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/content/pm/PackageManager;-FEATURE_BLUETOOTH-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothAssignedNumbers;-BLUETOOTH_SIG-I" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothA2dp;-ACTION_CONNECTION_STATE_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothA2dp;-ACTION_PLAYING_STATE_CHANGED-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothA2dp;-getConnectedDevices-()Ljava/util/List;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothA2dp;-getConnectionState-(Landroid/bluetooth/BluetoothDevice;)I" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothA2dp;-getDevicesMatchingConnectionStates-([I)Ljava/util/List;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothA2dp;-isA2dpPlaying-(Landroid/bluetooth/BluetoothDevice;)B" : "BLUETOOTH",
// 	"Landroid/provider/Settings/System;-AIRPLANE_MODE_RADIOS-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/provider/Settings/System;-BLUETOOTH_DISCOVERABILITY-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/provider/Settings/System;-BLUETOOTH_DISCOVERABILITY_TIMEOUT-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/provider/Settings/System;-BLUETOOTH_ON-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/provider/Settings/System;-RADIO_BLUETOOTH-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/provider/Settings/System;-VOLUME_BLUETOOTH_SCO-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothProfile;-getConnectedDevices-()Ljava/util/List;" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothProfile;-getConnectionState-(Landroid/bluetooth/BluetoothDevice;)I" : "BLUETOOTH",
// 	"Landroid/bluetooth/BluetoothProfile;-getDevicesMatchingConnectionStates-([I)Ljava/util/List;" : "BLUETOOTH",
// 	"Landroid/os/Process;-BLUETOOTH_GID-I" : "BLUETOOTH",
// 	"Landroid/provider/Settings;-ACTION_BLUETOOTH_SETTINGS-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/media/AudioManager;-ROUTE_BLUETOOTH-I" : "BLUETOOTH",
// 	"Landroid/media/AudioManager;-ROUTE_BLUETOOTH_A2DP-I" : "BLUETOOTH",
// 	"Landroid/media/AudioManager;-ROUTE_BLUETOOTH_SCO-I" : "BLUETOOTH",
// 	"Landroid/provider/Settings/Secure;-BLUETOOTH_ON-Ljava/lang/String;" : "BLUETOOTH",
// 	"Landroid/net/sip/SipAudioCall;-startAudio-()V" : "ACCESS_WIFI_STATE",
// 	"Landroid/app/ActivityManager;-moveTaskToFront-(I I)V" : "REORDER_TASKS",
// 	"Landroid/provider/Browser;-BOOKMARKS_URI-Landroid/net/Uri;" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-SEARCHES_URI-Landroid/net/Uri;" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-addSearchUrl-(Landroid/content/ContentResolver; Ljava/lang/String;)V" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-canClearHistory-(Landroid/content/ContentResolver;)B" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-getAllBookmarks-(Landroid/content/ContentResolver;)Landroid/database/Cursor;" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-getAllVisitedUrls-(Landroid/content/ContentResolver;)Landroid/database/Cursor;" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-requestAllIcons-(Landroid/content/ContentResolver; Ljava/lang/String; Landroid/webkit/WebIconDatabase/IconListener;)V" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-truncateHistory-(Landroid/content/ContentResolver;)V" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/provider/Browser;-updateVisitedHistory-(Landroid/content/ContentResolver; Ljava/lang/String; B)V" : "READ_HISTORY_BOOKMARKS",
// 	"Landroid/net/sip/SipAudioCall;-setSpeakerMode-(B)V" : "MODIFY_AUDIO_SETTINGS",
// 	"Landroid/media/AudioManager;-startBluetoothSco-()V" : "MODIFY_AUDIO_SETTINGS",
// 	"Landroid/media/AudioManager;-stopBluetoothSco-()V" : "MODIFY_AUDIO_SETTINGS",
// 	"Landroid/telephony/TelephonyManager;-ACTION_PHONE_STATE_CHANGED-Ljava/lang/String;" : "READ_PHONE_STATE",
// 	"Landroid/telephony/TelephonyManager; getDeviceId" : "READ_PHONE_STATE",
// 	"Landroid/telephony/TelephonyManager;-getDeviceSoftwareVersion-()Ljava/lang/String;" : "READ_PHONE_STATE",
// 	"Landroid/telephony/TelephonyManager;-getLine1Number-()Ljava/lang/String;" : "READ_PHONE_STATE",
// 	"Landroid/telephony/TelephonyManager;-getSimSerialNumber-()Ljava/lang/String;" : "READ_PHONE_STATE",
// 	"Landroid/telephony/TelephonyManager;-getSubscriberId-()Ljava/lang/String;" : "READ_PHONE_STATE",
// 	"Landroid/telephony/TelephonyManager;-getVoiceMailAlphaTag-()Ljava/lang/String;" : "READ_PHONE_STATE",
// 	"Landroid/telephony/TelephonyManager;-getVoiceMailNumber-()Ljava/lang/String;" : "READ_PHONE_STATE",
// 	"Landroid/telephony/PhoneStateListener;-LISTEN_CALL_FORWARDING_INDICATOR-I" : "READ_PHONE_STATE",
// 	"Landroid/telephony/PhoneStateListener;-LISTEN_CALL_STATE-I" : "READ_PHONE_STATE",
// 	"Landroid/telephony/PhoneStateListener;-LISTEN_DATA_ACTIVITY-I" : "READ_PHONE_STATE",
// 	"Landroid/telephony/PhoneStateListener;-LISTEN_MESSAGE_WAITING_INDICATOR-I" : "READ_PHONE_STATE",
// 	"Landroid/telephony/PhoneStateListener;-LISTEN_SIGNAL_STRENGTH-I" : "READ_PHONE_STATE",
// 	"Landroid/os/Build/VERSION_CODES;-DONUT-I" : "READ_PHONE_STATE",
//     };
// }